### PR TITLE
Spelling fix (ma"am » ma'am)

### PR DESCRIPTION
**Pull request by epan**
Source: http://www.merriam-webster.com/dictionary/ma'am

### CODE REVIEW

**Comment by hugovk** [comment]
@epan The [build failed](https://travis-ci.org/dariusk/corpora/builds/98476499). There's no need to escape the middle apostrophe, because double quotes are used for the string, not single quotes. So just remove that `\`.

**Comment by hugovk** [comment]
I've resubmitted this fix here: https://github.com/dariusk/corpora/pull/154.

**Comment by hugovk** [comment]
https://github.com/dariusk/corpora/pull/154 has been merged so this can be closed.

**Comment by epan** [comment]
thanks :+1:

**Pull request closed without merging**
