### PR TITLE
Add Tolkien_characterNames as another corpus

### PR DESCRIPTION
**Pull request by msbrown**
Character names from Tolkien's Middle Earth, from https://en.wikipedia.org/wiki/List_of_Middle-earth_characters. (Please feel free to add contribution in Readme)

### CODE REVIEW

**Comment by hugovk** [comment]
@msbrown Don't forget to name the file with a .json extenstion. 

Also perhaps name it tolkeinCharacterNames for consistency with the others in the same directory.

**Comment by hugovk** [comment]
And sorry for spamming, but would [/data/words/literature/](https://github.com/dariusk/corpora/tree/master/data/words/literature/) be a better home?

**Comment by dariusk** [comment]
Hmm. @hugovk, it's an interesting question. If we put this in `literature` then `spinalTapDrummers` should go in `movies` too. I think that, since this is where the names all hang out, we leave it in here.

**Comment by dariusk** [comment]
@msbrown Thanks for your submission!

**Pull request merged**
