### PR TITLE
Added new corpora for animals (ant & squid), geography, and medicine.…

### PR DESCRIPTION
**Pull request by ihh**
Some low-hanging fruit scraped from the OBO Foundry ontologies at http://www.obofoundry.org/

Scraper script can be found here: https://github.com/ihh/bracery/tree/master/import/obo

### CODE REVIEW

**Comment by ihh** [comment]
Some of this (eg diseases.json) overlaps with existing functionality (diagnoses.json), however "diagnoses" is derived from ICD-10 and so tends to be more influenced by operational clinical factors (e.g. billing, circumstances) whereas the OBO ontologies are generally more empirically grounded (and in particular diseases.json seems more etiologically focused)

**Comment by ihh** [comment]
Also added a few lists from miscellaneous sources including Wikipedia, Forbes, National Center for Education Statistics

**Comment by ihh** [comment]
> Some of these files are of the form:
> 
> ```json
> {
>  "description": "n/a",
>  "source": "n/a",
>  "entries":
>  [
>   ["femoral articular process of the metatrochanter"],
>   ["ventral metafurcal lamella"],
>   ["translucent patch"],
>   ["median mesofurco-mesotrochanteral muscle"],
>   ["pseudoceps"],
>   ["annulus"],
> ...
> ```
> 
> And some are like this:
> 
> ```json
> {
>   "description": "Academic subjects",
>   "source": "Classification of Instructional Programs (CIP 2000) https://nces.ed.gov/pubs2002/cip2000/",
>   "subjects": [
>     "Accounting",
>     "Administration of Special Education",
>     "Adult & Continuing Teacher Education",
>     "Advertising",
>     "African Studies",
>     "Afro-American Studies",
> ...
> ```
> 
> Would it be better to have them all in the latter form? It would make things more consistent and easier to access the data.

Yes, you're right. Thanks for catching this, I will fix it now

**Comment by dariusk** [comment]
Thank you for this contribution!!

**Pull request merged**
