### PR TITLE
add internet troll expletives

### PR DESCRIPTION
**Pull request by mannynotfound**
Common expletive words and spelling variations used to bypass filters on internet comments.

### CODE REVIEW

**Comment by dariusk** [comment]
Sorry, this is too completionist and a lot of this is scatological and not in line with the purpose the default word list. See the documentation for more on the philosophy behind the default list. Of course users can use the built-in functions to add or remove whatever words they want at runtime.

**Comment by hugovk** [comment]
@dariusk Are you mixing up this Corpora repo with https://github.com/dariusk/wordfilter?

**Comment by dariusk** [comment]
You are absolutely right, @hugovk. Apologies to @mannynotfound, I was just clearing out some `wordfilter` issues and got mixed up.

**Comment by dariusk** [comment]
@mannynotfound Feel free to resubmit the PR, I would've reopened it but I see your fork is deleted. If you don't want to do that I'm happy to manually add the data myself too.

**Pull request closed without merging**
