### PR TITLE
create google_material_colors.json

### PR DESCRIPTION
**Pull request by krisb1220**
Original Author: Kawanet 
Original File: https://gist.github.com/kawanet/a880c83f06d6baf742e45ac9ac52af96

### CODE REVIEW

**Comment by hugovk** [comment]
Please can you rename the file so it ends with a .json extension?

**Comment by krisb1220** [comment]
Sorry just saw this, should be fixed now

**Comment by dariusk** [comment]
Thanks @krisb1220! I moved the file to the `data/colors/` directory so it wasn't just hanging out in the root. [It's here now!](https://github.com/dariusk/corpora/blob/master/data/colors/google_material_colors.json)

**Comment by krisb1220** [comment]
Haha, I knew I was forgetting something! Thank you!

**Pull request merged**
