### PR TITLE
remove some potentially problematic words

### PR DESCRIPTION
**Pull request by coleww**
in the interests of punching up and not down, deletes some adjectives that I would personally not want my projects using for fear of saying something absolutely horrible.

I may have gone a bit too far in my deletions, lmk if you think anything should be un-deleted.

### CODE REVIEW

**Comment by dariusk** [comment]
Great contribution. Thanks.

**Comment by organisciak** [comment]
Thank you for noting these. Does anybody think that these words might be better annotated rather than outright removed? The change is ultimately inconsequential since it is intended to be an incomplete list, but most of these are legitimate non-charged words representing people's identities, so the symbolism of erasing a culture or gender identity from our vocabulary seems tricky. 

Still useful.

**Comment by coleww** [comment]
@organisciak i think if someone is making a bot that talks about people's identities they should be very thoughtful and intentional about how they do it, and maybe these words shouldn't be in a general purpose list. 

Like this bot is fantastic for example: https://twitter.com/restroomgender 

As I said, this is just erring on the side of "punching up and not down". If you want to add a list of nationalities or identities then by all means!

**Comment by dariusk** [comment]
Yeah, this is meant to be a sort of neutral list of placeholder adjectives for generic (mostly testing) purposes. There's a reason I don't block these words by default in my wordfilter module, but I think it's appropriate here.

**Pull request merged**
