### PR TITLE
US Domestic Airport Codes

### PR DESCRIPTION
**Pull request by msksfo**
This is a list of the major US commercial airports in each state, and their corresponding airport codes, both IATA and ICAO.

### CODE REVIEW

**Comment by hugovk** [comment]
"domestic" means something else to us non-US users of this repo :)

**Comment by ihh** [comment]
"US domestic" is unambiguous surely ;)

**Comment by msksfo** [comment]
Oh, I'm sorry Hugo!  I'm headed out now, but can try to make it more clear
later. Will I then need to submit a new pull request? (I'm very new to
git/github, and programming in general.)

~Tia

**Comment by hugovk** [comment]
If you commit to the same branch, and push, then this PR will be updated!

**Comment by dariusk** [comment]
@msksfo thanks so much for this contribution! Sorry for the delay in getting around to it. There's a technical problem with it (somehow it ended up a "submodule") but I am just gonna grab the file you gave me and file it in the `geography` folder.

**Comment by dariusk** [comment]
Okay, file is now here: https://github.com/dariusk/corpora/blob/master/data/geography/us_airport_codes.json

Thanks again @msksfo ✈️

**Pull request closed without merging**
