### PR TITLE
720 'phonetically balanced' Harvard Sentences

### PR DESCRIPTION
**Pull request by MichaelPaulukonis**
Added the 720 'phonetically balanced' Harvard Sentences with typo and spelling corrections.

Links to online sources included in the file.

To the best of my knowledge this text is considered public domain, having been created at Federal Expense in the 1940s, and has been widely used throughout the communications industry and academia since then.

### CODE REVIEW

**Comment by hugovk** [comment]
@MichaelPaulukonis This PR fails on Travis CI due to syntax problems. I've sent a PR to your branch which fixes it: https://github.com/MichaelPaulukonis/corpora/pull/1

**Comment by MichaelPaulukonis** [comment]
well, that was embarrassing.

**Comment by MichaelPaulukonis** [comment]
well, that was embarrassing.

**Comment by dariusk** [comment]
Thanks for this!

**Pull request merged**
