### PR TITLE
add list of bands that have opened for Tool :guitar:

### PR DESCRIPTION
**Pull request by coleww**
"Isis frontman Aaron Turner isn’t stupid. He knows his band is certain to get booed by Tool fans when Isis head out on the road with Maynard James Keenan’s collection of avant-metal cohorts. But that’s not going to stop Turner from trying to open up a few minds." http://www.mtv.com/news/1539033/tool-opening-act-isis-say-theyre-ready-to-be-booed-by-meatheads/

I'm probably gonna use this to make some sort of streaming-music-service playlist, but I could certainly see other uses for it.

### CODE REVIEW

**Comment by dariusk** [comment]
...this is maaaaaaaaaybe too specific for the scope of Corpora? IDK. I'll include it, since we have other weird sources. Mostly just registering my spidey sense for posterity here.

**Comment by coleww** [comment]
i initially hesitated to submit it, but i noticed a few other super ridiculously weird lists. 

could split off a fork for stuff-that-is-too-weird-for-corpora if it became a problem :joy_cat:

**Comment by dariusk** [comment]
Heh or just make it a `weird` branch

**Comment by coleww** [comment]
i do have a ton of gists of stuff that was definitely too weird/copyrighted for corpora (like every Seinfeld episode title, lists of common errors in the Ruby/Rails).

**Comment by enkiv2** [comment]
If there was a corpus that had stuff like seinfeld episode title lists, I'd
value the hell out of it, even if it ended up being a spinoff of this
project. (Core branch versus kitchen sink branch maybe?)

**Comment by organisciak** [comment]
About episode titles, not a copyright issue and unlikely a trademark issue: http://copyright.gov/circs/circ34.pdf . 

In the case of corpora, wouldn't 'weirder' be a more apt branch? :smirk:

**Comment by dariusk** [comment]
Haha, fair point.

**Comment by coleww** [comment]
https://github.com/coleww/weirdly-specific-corpora i renamed my fork to serve a higher purpose, and added some of my weirder lists. can merge stuff back here as needed/desired

**Pull request merged**
