### PR TITLE
Create epl_teams.json in new folder

### PR DESCRIPTION
**Pull request by SabareeshIyer**
Adding Football (soccer) teams in English Premier League to the data.
Will add other major leagues soon.

### CODE REVIEW

**Comment by hugovk** [comment]
Good stuff! I'd suggest just putting this in the `data/sports/` directory rather than `data/sports/Football (Soccer)/` as it can be good to avoid spaces and brackets in paths, and there's only one file in `data/sports/` so it's far from crowded.

**Comment by SabareeshIyer** [comment]
I chose to put it in a separate folder in case more sports get added in the future. It might be confusing if multiple leagues were in the names (as abbreviations, at that) without the sport being mentioned.
Would it be better to rename the folder to Football or Soccer instead?

**Comment by hugovk** [comment]
Yes, I think a lowercase football or soccer would be better :)

**Comment by SabareeshIyer** [comment]
Renamed accordingly.

**Pull request merged**
