### PR TITLE
added word clues from banana breakers (could also go in words?)

### PR DESCRIPTION
**Pull request by SimianLogic**
i made a scramble/boggle-like word game a couple of years ago called Banana Breakers that used 4/5/6 letter words to generate puzzles

the player could enter any word (simple dictionary check to see if it's a word), but i went through the entire dictionary of 4/5/6-letter words and hand-curated the common-ish and not-offensive words to be used as puzzle seeds.

for each word that could be used in a puzzle, I wrote 3+ "crossword clues" for that word -- mostly thesaurus words and short phrases that could evoke the target word. this was by far the grossest part of making that game, and if anyone else can use that data to make something interesting I'm all for it!

4-letter words: 1160
5-letter words: 1620
6-letter words: 1809

### CODE REVIEW

**Comment by dariusk** [comment]
Holy moly, what a great dataset! Thank you so much!

**Comment by dariusk** [comment]
Actually, could you move this to `words/` and then I'll merge? This has a lot of use for general language stuff, not just games.

**Comment by ckolderup** [comment]
Will, these files are amazing! Thank you so much!

**Comment by SimianLogic** [comment]
sure thing! moved it over to words

**Pull request merged**
