### PR TITLE
Added North American birds.

### PR DESCRIPTION
**Pull request by chrisspurgeon**
Here is a list of North American birds, as listed by the American Birding Association.

### CODE REVIEW

**Comment by dariusk** [comment]
This is suuuuper great but unfortunately I have to reject this because of the licensing on the ABA site:

````plaintext
Copyright © 2015 American Birding Association, Inc. No material displayed on the ABA website may be reproduced in any form without the express prior written consent of the ABA.
```

Thank you for including the source so I could verify this. Sorry it didn't work out. If you want to get written consent (per their license), I'd love to incorporate this.

**Comment by chrisspurgeon** [comment]
Those bastards! I'll ping them, and see if this usage is cool with them. Would you like me to cc you on the  emails?

Chris Spurgeon
chris@spurgeonworld.com

**Comment by ariddell** [comment]
It seems like fair use should apply here (assuming US Copyright law is the relevant law). [Mere facts are not copyrightable](https://en.wikipedia.org/wiki/Copyright_law_of_the_United_States#Compilations_of_facts_and_the_sweat_of_the_brow_doctrine) in the US. IANAL, but it seems like the American Birding Association's assertion of copyright is just another instance of copyfraud.

**Comment by chrisspurgeon** [comment]
Yeah, but you could argue that the ABA list is a creative work because it's a curated list... they decide for instance when a bird that historically only bred outside of North America has now established enough of a toehold in North America to merit inclusion.

I shot the ABA an email asking for permission, we'll see what they say.

**Comment by chrisspurgeon** [comment]
But fair use might still apply even though it might be considered a copyrighted work.

**Comment by ariddell** [comment]
From the Wikipedia summary of the relevant Supreme Court case:

> In regard to collections of facts, O'Connor stated that copyright can
> only apply to the creative aspects of collection: the creative choice of
> what data to include or exclude, the order and style in which the
> information is presented, etc., but not on the information itself. If
> Feist were to take the directory and rearrange it, it would destroy the
> copyright owned in the data. "Notwithstanding a valid copyright, a
> subsequent compiler remains free to use the facts contained in another's
> publication to aid in preparing a competing work, so long as the
> competing work does not feature the same selection and arrangement,"
> O'Connor wrote.

https://en.wikipedia.org/wiki/Feist_Publications,_Inc.,_v._Rural_Telephone_Service_Co.

That the list is "curated" isn't the issue (or even well-defined).

Of course the law is completely different in the UK and EU.

**Comment by chrisspurgeon** [comment]
Hey, check it out! The American Birding Association says it's fine to use their checklist! Here's my email exchange with them...

---------------

Hi Chris,

That is fine with us. Please link back to the ABA Checklist page:

http://listing.aba.org/aba-checklist/

Cheers,

-greg neise


Greg Neise 
Web Developer, Blogger, Editor: Big Day & List Report
email: gneise@aba.org


On Aug 19, 2015, at 2:14 PM, Chris Spurgeon <chris@spurgeonworld.com> wrote:

The following was submitted by Chris Spurgeon (Email: chris@spurgeonworld.com; Phone: 213-xxx-xxxx).
Comment/Question:  Hi!

I'm a computer programmer (as well as a birder and ABA member!) and would like to ask permission to use the ABA checklist in some computer code.

I and many other volunteers contribute to a project called copora; it's a collection of lists that programmers can use in the projects -- everything from a list of all the world's major rivers to every object likely to be found in the average household. (You can see the project at https://github.com/dariusk/corpora ).

We already have listings of birds for two regions (Antarctica and the UK) and I'd like to add North American birds. Since ABA is an authoritative source, I'd love if we could use the ABA list. We'll of course give the ABA credit, and provide a link to the ABA website.

Hoping you'll say yes!

Chris Spurgeon
chris@spurgeonworld.com

------- 

So, I think we're good to go if you'd like to use the North American bird list. Sweet!

Chris

**Comment by dariusk** [comment]
Wonderful!!!! Thank you for doing the legwork, @chrisspurgeon

**Pull request merged**
