### PR TITLE
female_classical_guitarists.json

### PR DESCRIPTION
**Pull request by jesushilariohernandez**
Hello, Here is another JSON data list! ...I like data! :)

### CODE REVIEW

**Comment by hugovk** [comment]
@jesushilariohernandez Everything in this repo is a list, so how about renaming the file from a_list_ of_female_classical_guitarists to the more concise female_classical_guitarists.json? And don't forget the .json extension :)

**Comment by jesushilariohernandez** [comment]
right. thanks!

**Comment by jesushilariohernandez** [comment]
It's changed

**Comment by dariusk** [comment]
Thanks!

**Pull request merged**
